const json = {
    "supportVideoPlay":true,
    "code":0,
    "size":4,
    "data":[
        {
            "groups":[
                {
                    "groupName":"系统版本",
                    "item":[
                        {
                            "readonly":1,
                            "name":"设备内核",
                            "type":"string",
                            "value":"4.9.84 #8 PREEMPT Fri Jul 19 12:38:05 CST 2019",
                            "key":"kernel_version",
                            "maxLength":128
                        },
                        {
                            "readonly":1,
                            "name":"文件系统",
                            "type":"string",
                            "value":"3.0.1 2019-06-28 14:00",
                            "key":"filesystem_version",
                            "maxLength":64
                        },
                        {
                            "readonly":1,
                            "name":"业务软件",
                            "type":"string",
                            "value":"9.0.23_2019-12-02_16:30 EVXnn2-C",
                            "key":"app_version",
                            "maxLength":64
                        }
                    ],
                    "groupKey":"system_version"
                },
                {
                    "groupName":"时间同步",
                    "item":[
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2,
                                3,
                                4,
                                5,
                                6,
                                7,
                                8,
                                9,
                                10,
                                11,
                                12,
                                13,
                                14,
                                15,
                                16,
                                17,
                                18,
                                19,
                                20,
                                21,
                                22,
                                23,
                                24
                            ],
                            "name":"时区",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "(西十二区)夸贾林岛",
                                "(西十一区)中途岛",
                                "(西十区)夏威夷岛",
                                "(西九区)阿拉斯加",
                                "(西八区)蒂华纳",
                                "(西七区)亚利桑那",
                                "(西六区)墨西哥城",
                                "(西五区)印地安那州",
                                "(西四区)加拉加斯",
                                "(西三区)巴西利亚",
                                "(西二区)中大西洋",
                                "(西一区)亚速尔群岛",
                                "(零时区)伦敦",
                                "(东一区)阿姆斯特丹",
                                "(东二区)哈拉雷",
                                "(东三区)巴格达",
                                "(东四区)阿布扎比",
                                "(东五区)叶卡特琳堡",
                                "(东六区)阿拉木图",
                                "(东七区)曼谷",
                                "(东八区)北京",
                                "(东九区)平壤",
                                "(东十区)布里斯班",
                                "(东十一区)马加丹",
                                "(东十二区)奥克兰"
                            ],
                            "value":20,
                            "key":"time_zone"
                        },
                        {
                            "readonly":0,
                            "name":"系统时间",
                            "type":"string",
                            "value":"2021-08-09 18:02:47",
                            "key":"system_time",
                            "maxLength":20
                        },
                        {
                            "readonly":0,
                            "name":"NTP使能",
                            "type":"boolean",
                            "value":0,
                            "key":"ntp_enable"
                        },
                        {
                            "readonly":0,
                            "name":"NTP服务器地址",
                            "type":"string",
                            "value":"cn.ntp.org.cn",
                            "key":"ntp_server_address",
                            "maxLength":64
                        },
                        {
                            "minValue":1,
                            "readonly":0,
                            "maxValue":65535,
                            "name":"NTP服务器端口",
                            "type":"integer",
                            "value":123,
                            "key":"ntp_server_port"
                        }
                    ],
                    "groupKey":"time_sync"
                },
                {
                    "groupName":"设备信息",
                    "item":[
                        {
                            "readonly":0,
                            "name":"地区编号",
                            "type":"string",
                            "value":"0755",
                            "key":"area_number",
                            "maxLength":16
                        },
                        {
                            "readonly":0,
                            "name":"项目名称",
                            "type":"string",
                            "value":"default",
                            "key":"project_name",
                            "maxLength":64
                        },
                        {
                            "readonly":0,
                            "name":"设备编号",
                            "type":"string",
                            "value":"00000",
                            "key":"device_number",
                            "maxLength":16
                        },
                        {
                            "readonly":0,
                            "name":"出入口名称",
                            "type":"string",
                            "value":"default",
                            "key":"road_name",
                            "maxLength":64
                        },
                        {
                            "readonly":0,
                            "name":"出入口编号",
                            "type":"string",
                            "value":"00000",
                            "key":"road_number",
                            "maxLength":16
                        },
                        {
                            "readonly":1,
                            "name":"相机序列号",
                            "type":"string",
                            "value":"64581f81d6e2db15",
                            "key":"license_number",
                            "maxLength":64
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                1,
                                2
                            ],
                            "name":"方位",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "入口",
                                "出口"
                            ],
                            "value":1,
                            "key":"direction"
                        }
                    ],
                    "groupKey":"device_information"
                },
                {
                    "groupName":"网络设置",
                    "item":[
                        {
                            "readonly":1,
                            "name":"MAC地址",
                            "type":"string",
                            "value":"90:70:66:0C:FA:DC",
                            "key":"mac_address",
                            "maxLength":32
                        },
                        {
                            "readonly":1,
                            "name":"IP地址",
                            "type":"string",
                            "value":"192.168.8.11",
                            "key":"ip_address",
                            "maxLength":32
                        },
                        {
                            "readonly":1,
                            "name":"子网掩码",
                            "type":"string",
                            "value":"255.255.255.0",
                            "key":"mask_address",
                            "maxLength":32
                        },
                        {
                            "readonly":1,
                            "name":"默认网关",
                            "type":"string",
                            "value":"192.168.8.1",
                            "key":"gateway_address",
                            "maxLength":32
                        },
                        {
                            "readonly":1,
                            "name":"DNS服务器",
                            "type":"string",
                            "value":"192.168.8.1",
                            "key":"dns_address",
                            "maxLength":32
                        }
                    ],
                    "groupKey":"network_setup"
                },
                {
                    "groupName":"串口通信1",
                    "item":[
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2,
                                3,
                                4,
                                5,
                                6,
                                7
                            ],
                            "name":"波特率",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "1200",
                                "2400",
                                "4800",
                                "9600",
                                "19200",
                                "38400",
                                "57600",
                                "115200"
                            ],
                            "value":4,
                            "key":"baudrate"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                5,
                                6,
                                7,
                                8
                            ],
                            "name":"数据位",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "5",
                                "6",
                                "7",
                                "8"
                            ],
                            "value":8,
                            "key":"databit"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                1,
                                2
                            ],
                            "name":"停止位",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "1",
                                "2"
                            ],
                            "value":0,
                            "key":"stopbit"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2,
                                3,
                                4
                            ],
                            "name":"校验位",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "无校验",
                                "奇校验",
                                "偶校验",
                                "标志校验",
                                "空校验"
                            ],
                            "value":0,
                            "key":"checktype"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2
                            ],
                            "name":"功能",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "透传控制",
                                "屏显控制",
                                "广播模式"
                            ],
                            "value":1,
                            "key":"function"
                        }
                    ],
                    "groupKey":"serial1_port_setup"
                },
                {
                    "groupName":"串口通信2",
                    "item":[
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2,
                                3,
                                4,
                                5,
                                6,
                                7
                            ],
                            "name":"波特率",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "1200",
                                "2400",
                                "4800",
                                "9600",
                                "19200",
                                "38400",
                                "57600",
                                "115200"
                            ],
                            "value":4,
                            "key":"baudrate"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                5,
                                6,
                                7,
                                8
                            ],
                            "name":"数据位",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "5",
                                "6",
                                "7",
                                "8"
                            ],
                            "value":8,
                            "key":"databit"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                1,
                                2
                            ],
                            "name":"停止位",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "1",
                                "2"
                            ],
                            "value":1,
                            "key":"stopbit"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2,
                                3,
                                4
                            ],
                            "name":"校验位",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "无校验",
                                "奇校验",
                                "偶校验",
                                "标志校验",
                                "空校验"
                            ],
                            "value":0,
                            "key":"checktype"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2
                            ],
                            "name":"功能",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "透传控制",
                                "屏显控制",
                                "广播模式"
                            ],
                            "value":0,
                            "key":"function"
                        }
                    ],
                    "groupKey":"serial2_port_setup"
                },
                {
                    "groupName":"HTTP推送",
                    "item":[
                        {
                            "readonly":0,
                            "name":"是否启用",
                            "type":"boolean",
                            "value":0,
                            "key":"enable"
                        },
                        {
                            "readonly":0,
                            "name":"服务器地址",
                            "type":"string",
                            "value":"192.168.0.100",
                            "key":"ip_address",
                            "maxLength":16
                        },
                        {
                            "readonly":0,
                            "name":"服务器备用地址",
                            "type":"string",
                            "value":"",
                            "key":"backup_ip_address",
                            "maxLength":64
                        },
                        {
                            "minValue":1,
                            "readonly":0,
                            "maxValue":65535,
                            "name":"端口",
                            "type":"integer",
                            "value":80,
                            "key":"port"
                        },
                        {
                            "minValue":1,
                            "readonly":0,
                            "maxValue":65535,
                            "name":"超时时间",
                            "type":"integer",
                            "value":5,
                            "key":"timeout"
                        },
                        {
                            "readonly":0,
                            "name":"推送车牌是否开启",
                            "type":"boolean",
                            "value":0,
                            "key":"palate_enable"
                        },
                        {
                            "readonly":0,
                            "name":"地址",
                            "type":"string",
                            "value":"",
                            "key":"plate_address",
                            "maxLength":127
                        },
                        {
                            "readonly":0,
                            "name":"发送图片",
                            "type":"boolean",
                            "value":0,
                            "key":"big_picture_enable"
                        },
                        {
                            "readonly":0,
                            "name":"发送小图片",
                            "type":"boolean",
                            "value":0,
                            "key":"small_picture_enable"
                        },
                        {
                            "readonly":0,
                            "name":"推送端口触发信息",
                            "type":"boolean",
                            "value":0,
                            "key":"gpio_push_enable"
                        },
                        {
                            "readonly":0,
                            "name":"地址",
                            "type":"string",
                            "value":"",
                            "key":"gpio_address",
                            "maxLength":65
                        },
                        {
                            "readonly":0,
                            "name":"推送串口信息",
                            "type":"boolean",
                            "value":0,
                            "key":"serial_push_enable"
                        },
                        {
                            "readonly":0,
                            "name":"地址",
                            "type":"string",
                            "value":"",
                            "key":"serial_address",
                            "maxLength":63
                        },
                        {
                            "readonly":0,
                            "name":"HTTP心跳",
                            "type":"boolean",
                            "value":0,
                            "key":"heartbeat_enable"
                        },
                        {
                            "readonly":0,
                            "name":"地址",
                            "type":"string",
                            "value":"",
                            "key":"heartbeat_address",
                            "maxLength":80
                        },
                        {
                            "minValue":1,
                            "readonly":0,
                            "maxValue":65535,
                            "name":"心跳间隔",
                            "type":"integer",
                            "value":5,
                            "key":"heartbeat_interval"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1
                            ],
                            "name":"字符编码",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "GB2312",
                                "UTF-8"
                            ],
                            "value":1,
                            "key":"character_encoding"
                        },
                        {
                            "readonly":0,
                            "name":"SSL连接",
                            "type":"boolean",
                            "value":0,
                            "key":"ssl_enable"
                        },
                        {
                            "minValue":1,
                            "readonly":0,
                            "maxValue":65535,
                            "name":"SSL端口",
                            "type":"integer",
                            "value":443,
                            "key":"ssl_port"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1
                            ],
                            "name":"验证方式",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "匿名",
                                "CA证书"
                            ],
                            "value":0,
                            "key":"verify_way"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2,
                                3
                            ],
                            "name":"私有协议",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "不启用",
                                "启用协议1",
                                "启用协议2",
                                "启用协议3"
                            ],
                            "value":0,
                            "key":"private_protocol"
                        }
                    ],
                    "groupKey":"http_push_setup"
                },
                {
                    "groupName":"车牌多次推送",
                    "item":[
                        {
                            "readonly":0,
                            "name":"是否启用",
                            "type":"boolean",
                            "value":0,
                            "key":"enable"
                        },
                        {
                            "readonly":0,
                            "name":"发送大图",
                            "type":"boolean",
                            "value":0,
                            "key":"big_picture_enable"
                        },
                        {
                            "readonly":0,
                            "name":"发送小图",
                            "type":"boolean",
                            "value":0,
                            "key":"small_picture_enable"
                        },
                        {
                            "readonly":0,
                            "name":"无岗亭模式",
                            "type":"boolean",
                            "value":0,
                            "key":"watch_house_enable"
                        }
                    ],
                    "groupKey":"plate_result_push_setup"
                },
                {
                    "groupName":"远程维护",
                    "item":[
                        {
                            "readonly":0,
                            "name":"远程维护功能",
                            "type":"boolean",
                            "value":1,
                            "key":"enable"
                        },
                        {
                            "readonly":0,
                            "name":"远程服务地址",
                            "type":"string",
                            "value":"message.qy-vds.com",
                            "key":"cloud_address",
                            "maxLength":64
                        },
                        {
                            "minValue":1,
                            "readonly":0,
                            "maxValue":65535,
                            "name":"远程服务端口",
                            "type":"integer",
                            "value":5080,
                            "key":"cloud_port"
                        },
                        {
                            "readonly":0,
                            "name":"发送图片",
                            "type":"boolean",
                            "value":0,
                            "key":"big_picture_enable"
                        },
                        {
                            "readonly":0,
                            "name":"发送小图片",
                            "type":"boolean",
                            "value":0,
                            "key":"small_picture_enable"
                        },
                        {
                            "readonly":0,
                            "name":"发送视频",
                            "type":"boolean",
                            "value":1,
                            "key":"video_enable"
                        }
                    ],
                    "groupKey":"remote_debug_setup"
                },
                {
                    "groupName":"识别区域",
                    "item":[
                        {
                            "readonly":0,
                            "name":"识别区域",
                            "type":"string",
                            "value":""
                        },
                        {
                            "readonly":0,
                            "name":"来向抓拍线",
                            "type":"string",
                            "value":"[{\"x\":5,\"y\":615},{\"x\":1840,\"y\":445}]",
                            "key":"downline",
                            "maxLength":512
                        },
                        {
                            "readonly":0,
                            "name":"去向抓拍线",
                            "type":"string",
                            "value":"[{\"x\":5,\"y\":425},{\"x\":1810,\"y\":300}]",
                            "key":"upline",
                            "maxLength":512
                        }
                    ],
                    "visible":false,
                    "groupKey":"region"
                }
            ],
            "classifyKey":"base_config",
            "classifyName":"基本配置"
        },
        {
            "groups":[
                {
                    "groupName":"识别配置",
                    "item":[
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2,
                                3,
                                4,
                                5,
                                6,
                                7,
                                8,
                                9,
                                10,
                                11,
                                12,
                                13,
                                14,
                                15,
                                16,
                                17,
                                18,
                                19,
                                20,
                                21,
                                22,
                                23,
                                24,
                                25,
                                26,
                                27,
                                28,
                                29,
                                30,
                                31
                            ],
                            "name":"默认省份",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "京",
                                "津",
                                "沪",
                                "渝",
                                "冀",
                                "晋",
                                "辽",
                                "吉",
                                "黑",
                                "苏",
                                "浙",
                                "皖",
                                "闽",
                                "赣",
                                "鲁",
                                "豫",
                                "鄂",
                                "湘",
                                "粤",
                                "琼",
                                "川",
                                "贵",
                                "云",
                                "陕",
                                "甘",
                                "宁",
                                "青",
                                "藏",
                                "桂",
                                "蒙",
                                "新",
                                "全国"
                            ],
                            "value":31,
                            "key":"province"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2,
                                3,
                                4,
                                5,
                                6,
                                7,
                                8,
                                9,
                                10,
                                11,
                                12,
                                13,
                                14,
                                15,
                                16,
                                17,
                                18,
                                19,
                                20,
                                21,
                                22,
                                23,
                                24
                            ],
                            "name":"默认城市",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "A",
                                "B",
                                "C",
                                "D",
                                "E",
                                "F",
                                "G",
                                "H",
                                "J",
                                "K",
                                "L",
                                "M",
                                "N",
                                "P",
                                "Q",
                                "R",
                                "S",
                                "T",
                                "U",
                                "V",
                                "W",
                                "X",
                                "Y",
                                "Z",
                                "全省"
                            ],
                            "value":24,
                            "key":"city"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2
                            ],
                            "name":"车牌大小",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "80-200",
                                "80-400",
                                "160-400"
                            ],
                            "value":1,
                            "key":"vehicle_size"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                1,
                                2,
                                3
                            ],
                            "name":"误报处理等级",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "低",
                                "中",
                                "高"
                            ],
                            "value":2,
                            "key":"invalid_level"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2,
                                3,
                                4,
                                5,
                                6,
                                7,
                                8,
                                9,
                                10,
                                11,
                                12,
                                13,
                                14,
                                15,
                                16,
                                17
                            ],
                            "name":"抓拍灵敏度",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "低",
                                "中",
                                "高 85",
                                "高 86",
                                "高 87",
                                "高 88",
                                "高 89",
                                "高 90",
                                "高 91",
                                "高 92",
                                "高 93",
                                "高 94",
                                "高 95",
                                "高 96",
                                "高 97",
                                "高 98",
                                "高 99",
                                "高 100"
                            ],
                            "value":1,
                            "key":"plate_sensitivity"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2
                            ],
                            "name":"抓拍方向",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "去向",
                                "来向",
                                "双向"
                            ],
                            "value":1,
                            "key":"plate_direction"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1
                            ],
                            "name":"抓拍精度",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "最高",
                                "最优"
                            ],
                            "value":1,
                            "key":"plate_precision"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2,
                                3,
                                4,
                                5,
                                6
                            ],
                            "name":"同一辆车抓拍间隔(秒)",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "15",
                                "30",
                                "45",
                                "60",
                                "90",
                                "120",
                                "150"
                            ],
                            "value":1,
                            "key":"plate_interval"
                        },
                        {
                            "readonly":0,
                            "name":"异常车牌不上报",
                            "type":"boolean",
                            "value":0,
                            "key":"noreport_abnormal"
                        },
                        {
                            "readonly":0,
                            "name":"车牌特写",
                            "type":"boolean",
                            "value":1,
                            "key":"plate_feature"
                        },
                        {
                            "readonly":0,
                            "name":"车牌显示识别区",
                            "type":"boolean",
                            "value":1,
                            "key":"plate_rec_show"
                        },
                        {
                            "readonly":0,
                            "name":"输出武警汉字",
                            "type":"boolean",
                            "value":0,
                            "key":"police_plate"
                        },
                        {
                            "readonly":0,
                            "name":"显示实时车牌",
                            "type":"boolean",
                            "value":0,
                            "key":"plate_realtime_show"
                        },
                        {
                            "readonly":0,
                            "name":"无车牌抓拍",
                            "type":"boolean",
                            "value":0,
                            "key":"noplate_snap"
                        }
                    ],
                    "groupKey":"vehicle_identify_setup"
                },
                {
                    "groupName":"识别类型",
                    "item":[
                        {
                            "readonly":0,
                            "name":"蓝牌",
                            "type":"boolean",
                            "value":1,
                            "key":"plate_blue"
                        },
                        {
                            "readonly":0,
                            "name":"黄牌",
                            "type":"boolean",
                            "value":1,
                            "key":"plate_yellow"
                        },
                        {
                            "readonly":0,
                            "name":"黑牌",
                            "type":"boolean",
                            "value":1,
                            "key":"plate_black"
                        },
                        {
                            "readonly":0,
                            "name":"教练牌",
                            "type":"boolean",
                            "value":1,
                            "key":"plate_jiaolian"
                        },
                        {
                            "readonly":0,
                            "name":"警牌",
                            "type":"boolean",
                            "value":1,
                            "key":"plate_jinche"
                        },
                        {
                            "readonly":0,
                            "name":"武警牌",
                            "type":"boolean",
                            "value":1,
                            "key":"plate_wujing"
                        },
                        {
                            "readonly":0,
                            "name":"军牌",
                            "type":"boolean",
                            "value":1,
                            "key":"plate_army"
                        },
                        {
                            "readonly":0,
                            "name":"港澳牌",
                            "type":"boolean",
                            "value":1,
                            "key":"plate_gangao"
                        },
                        {
                            "readonly":0,
                            "name":"使馆牌",
                            "type":"boolean",
                            "value":1,
                            "key":"plate_shiguan"
                        },
                        {
                            "readonly":0,
                            "name":"新能源牌",
                            "type":"boolean",
                            "value":1,
                            "key":"plate_new"
                        },
                        {
                            "readonly":0,
                            "name":"民航牌",
                            "type":"boolean",
                            "value":1,
                            "key":"plate_minhang"
                        },
                        {
                            "readonly":0,
                            "name":"摩托车牌",
                            "type":"boolean",
                            "value":1,
                            "key":"plate_motor"
                        },
                        {
                            "readonly":0,
                            "name":"应急牌",
                            "type":"boolean",
                            "value":1,
                            "key":"plate_yingji"
                        }
                    ],
                    "groupKey":"vehicle_identify_type_setup"
                },
                {
                    "groupName":"视频字幕",
                    "item":[
                        {
                            "readonly":0,
                            "name":"显示时间",
                            "type":"boolean",
                            "value":1,
                            "key":"time_display"
                        },
                        {
                            "readonly":0,
                            "name":"字幕1使能",
                            "type":"boolean",
                            "value":0,
                            "key":"subtitle1_enable"
                        },
                        {
                            "readonly":0,
                            "name":"字幕1内容",
                            "type":"string",
                            "value":"",
                            "key":"subtitle1_content",
                            "maxLength":66
                        },
                        {
                            "readonly":0,
                            "name":"字幕2使能",
                            "type":"boolean",
                            "value":0,
                            "key":"subtitle2_enable"
                        },
                        {
                            "readonly":0,
                            "name":"字幕2内容",
                            "type":"string",
                            "value":"",
                            "key":"subtitle2_content",
                            "maxLength":66
                        },
                        {
                            "readonly":0,
                            "name":"字幕3使能",
                            "type":"boolean",
                            "value":0,
                            "key":"subtitle3_enable"
                        },
                        {
                            "readonly":0,
                            "name":"字幕3内容",
                            "type":"string",
                            "value":"",
                            "key":"subtitle3_content",
                            "maxLength":66
                        },
                        {
                            "readonly":0,
                            "name":"字幕4使能",
                            "type":"boolean",
                            "value":0,
                            "key":"subtitle4_enable"
                        },
                        {
                            "readonly":0,
                            "name":"字幕4内容",
                            "type":"string",
                            "value":"",
                            "key":"subtitle4_content",
                            "maxLength":66
                        }
                    ],
                    "groupKey":"video_subtitle"
                },
                {
                    "groupName":"图片字幕",
                    "item":[
                        {
                            "readonly":0,
                            "name":"时间",
                            "type":"boolean",
                            "value":1,
                            "key":"time_enable"
                        },
                        {
                            "readonly":0,
                            "name":"车型",
                            "type":"boolean",
                            "value":1,
                            "key":"vehicle_size_enable"
                        },
                        {
                            "readonly":0,
                            "name":"车牌",
                            "type":"boolean",
                            "value":1,
                            "key":"vehicle_plate_enable"
                        },
                        {
                            "readonly":0,
                            "name":"车牌宽度",
                            "type":"boolean",
                            "value":1,
                            "key":"plate_pixel_enable"
                        },
                        {
                            "readonly":0,
                            "name":"车牌颜色",
                            "type":"boolean",
                            "value":1,
                            "key":"vehicle_color_enable"
                        }
                    ],
                    "groupKey":"picture_subtitle"
                },
                {
                    "groupName":"视频参数",
                    "item":[
                        {
                            "readonly":0,
                            "optionValue":[
                                1,
                                2
                            ],
                            "name":"快门模式",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "手动",
                                "自动"
                            ],
                            "value":2,
                            "key":"shutter_mode"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2,
                                3,
                                4,
                                5,
                                6,
                                7,
                                8
                            ],
                            "name":"快门上限",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "20",
                                "100",
                                "200",
                                "500",
                                "1000",
                                "2500",
                                "4000",
                                "5000",
                                "10000"
                            ],
                            "value":7,
                            "key":"shutter_value"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                1,
                                2
                            ],
                            "name":"增益模式",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "手动",
                                "自动"
                            ],
                            "value":2,
                            "key":"gain_mode"
                        },
                        {
                            "minValue":0,
                            "readonly":0,
                            "maxValue":15,
                            "name":"增益上限",
                            "type":"integer",
                            "value":5,
                            "key":"gain_value"
                        },
                        {
                            "minValue":0,
                            "readonly":0,
                            "maxValue":100,
                            "name":"图片亮度",
                            "type":"integer",
                            "value":40,
                            "key":"brightness"
                        },
                        {
                            "minValue":0,
                            "readonly":0,
                            "maxValue":100,
                            "name":"图片质量",
                            "type":"integer",
                            "value":30,
                            "key":"picture_quality"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2,
                                3
                            ],
                            "name":"图片大小",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "1080P(1920x1080)",
                                "720P(1280x720)",
                                "4CIF(704x576)",
                                "CIF(352x288)"
                            ],
                            "value":0,
                            "key":"picture_size"
                        },
                        {
                            "readonly":0,
                            "name":"宽动态开启",
                            "type":"boolean",
                            "value":0,
                            "key":"wdr_enable"
                        },
                        {
                            "readonly":0,
                            "name":"顺光逆光开启",
                            "type":"boolean",
                            "value":1,
                            "key":"ev_enable"
                        }
                    ],
                    "groupKey":"video_param"
                },
                {
                    "groupName":"主视频编码",
                    "item":[
                        {
                            "readonly":0,
                            "optionValue":[
                                2,
                                4
                            ],
                            "name":"分辨率",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "4CIF(704x576)",
                                "720P(1280x720)"
                            ],
                            "value":2,
                            "key":"resolution"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1
                            ],
                            "name":"码率控制",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "VBR",
                                "CBR"
                            ],
                            "value":0,
                            "key":"rate_control"
                        },
                        {
                            "minValue":384000,
                            "readonly":0,
                            "maxValue":16000000,
                            "name":"码率",
                            "type":"integer",
                            "value":1000,
                            "key":"bit_rate"
                        },
                        {
                            "minValue":1,
                            "readonly":0,
                            "maxValue":5,
                            "name":"I帧间隔",
                            "type":"integer",
                            "value":2,
                            "key":"Iframe_period"
                        },
                        {
                            "minValue":1,
                            "readonly":0,
                            "maxValue":25,
                            "name":"帧频",
                            "type":"integer",
                            "value":25,
                            "key":"frame_rate"
                        }
                    ],
                    "groupKey":"main_video"
                },
                {
                    "groupName":"脱机收费",
                    "item":[
                        {
                            "readonly":0,
                            "optionValue":[
                                1,
                                2,
                                3
                            ],
                            "name":"脱机收费模式",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "脱机使能",
                                "强制使能",
                                "不使能"
                            ],
                            "value":3,
                            "key":"offline_mode"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                1,
                                2
                            ],
                            "name":"LED显示屏方位配置",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "入口",
                                "出口"
                            ],
                            "value":1,
                            "key":"screen_position"
                        },
                        {
                            "readonly":0,
                            "name":"入口临时车自动放行",
                            "type":"boolean",
                            "value":0,
                            "key":"entrance_vehicle_release"
                        },
                        {
                            "readonly":0,
                            "name":"出口临时车收费为0时自动放行",
                            "type":"boolean",
                            "value":0,
                            "key":"exit_vehicle_release"
                        },
                        {
                            "readonly":0,
                            "name":"出口所有车放行",
                            "type":"boolean",
                            "value":0,
                            "key":"all_release"
                        }
                    ],
                    "groupKey":"offline"
                },
                {
                    "groupName":"组播配置",
                    "item":[
                        {
                            "readonly":0,
                            "name":"组播地址",
                            "type":"string",
                            "value":"239.24.138.40",
                            "key":"multicast_address",
                            "maxLength":20
                        },
                        {
                            "minValue":1,
                            "readonly":0,
                            "maxValue":65535,
                            "name":"组播端口",
                            "type":"integer",
                            "value":20000,
                            "key":"multicast_port"
                        }
                    ],
                    "groupKey":"multicast"
                }
            ],
            "classifyKey":"work_config",
            "classifyName":"业务配置"
        },
        {
            "groups":[
                {
                    "groupName":"补光配置",
                    "item":[
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2
                            ],
                            "name":"补光模式",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "强制关",
                                "强制开",
                                "自动"
                            ],
                            "value":1,
                            "key":"work_mode"
                        },
                        {
                            "minValue":1,
                            "readonly":0,
                            "maxValue":7,
                            "name":"补光等级",
                            "type":"integer",
                            "value":5,
                            "key":"level"
                        },
                        {
                            "minValue":1,
                            "readonly":0,
                            "maxValue":100,
                            "name":"开启阀值",
                            "type":"integer",
                            "value":35,
                            "key":"threshold"
                        }
                    ],
                    "groupKey":"light_config"
                },
                {
                    "groupName":"检测方式",
                    "item":[
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                2,
                                3
                            ],
                            "name":"检测模式",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "线圈",
                                "视频",
                                "线圈+视频"
                            ],
                            "value":2,
                            "key":"detect_mode"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2,
                                3,
                                4
                            ],
                            "name":"输入检测",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "断开有车",
                                "闭合有车",
                                "高电平有车",
                                "低电平有车",
                                "变化上报"
                            ],
                            "value":1,
                            "key":"input_detect"
                        },
                        {
                            "minValue":0,
                            "readonly":0,
                            "maxValue":200,
                            "name":"延时时长",
                            "type":"integer",
                            "value":100,
                            "key":"loop_interval"
                        }
                    ],
                    "groupKey":"test_way"
                },
                {
                    "groupName":"强制开闸控制",
                    "item":[
                        {
                            "readonly":0,
                            "name":"时段1",
                            "type":"boolean",
                            "value":0,
                            "key":"time1_enable"
                        },
                        {
                            "readonly":0,
                            "name":"时段1开始-结束时间",
                            "type":"string",
                            "value":"00:00-00:00",
                            "key":"time1_start_end",
                            "maxLength":11
                        },
                        {
                            "readonly":0,
                            "name":"时段2",
                            "type":"boolean",
                            "value":0,
                            "key":"time2_enable"
                        },
                        {
                            "readonly":0,
                            "name":"时段2开始-结束时间",
                            "type":"string",
                            "value":"00:00-00:00",
                            "key":"time2_start_end",
                            "maxLength":11
                        },
                        {
                            "readonly":0,
                            "name":"时段3",
                            "type":"boolean",
                            "value":0,
                            "key":"time13_enable"
                        },
                        {
                            "readonly":0,
                            "name":"时段3开始-结束时间",
                            "type":"string",
                            "value":"00:00-00:00",
                            "key":"time3_start_end",
                            "maxLength":11
                        }
                    ],
                    "groupKey":"force_open_door"
                },
                {
                    "groupName":"LED强制开控制",
                    "item":[
                        {
                            "readonly":0,
                            "name":"时段1",
                            "type":"boolean",
                            "value":0,
                            "key":"time1_enable"
                        },
                        {
                            "minValue":1,
                            "readonly":0,
                            "maxValue":7,
                            "name":"时段1亮度等级",
                            "type":"integer",
                            "value":1,
                            "key":"time1_led_level"
                        },
                        {
                            "readonly":0,
                            "name":"时段1开始-结束时间",
                            "type":"string",
                            "value":"00:00-00:00",
                            "key":"time1_start_end",
                            "maxLength":11
                        },
                        {
                            "readonly":0,
                            "name":"时段2",
                            "type":"boolean",
                            "value":0,
                            "key":"time2_enable"
                        },
                        {
                            "minValue":1,
                            "readonly":0,
                            "maxValue":7,
                            "name":"时段2亮度等级",
                            "type":"integer",
                            "value":1,
                            "key":"time2_led_level"
                        },
                        {
                            "readonly":0,
                            "name":"时段2开始-结束时间",
                            "type":"string",
                            "value":"00:00-00:00",
                            "key":"time2_start_end",
                            "maxLength":11
                        },
                        {
                            "readonly":0,
                            "name":"时段3",
                            "type":"boolean",
                            "value":0,
                            "key":"time3_enable"
                        },
                        {
                            "minValue":1,
                            "readonly":0,
                            "maxValue":7,
                            "name":"时段3亮度等级",
                            "type":"integer",
                            "value":1,
                            "key":"time3_led_level"
                        },
                        {
                            "readonly":0,
                            "name":"时段3开始-结束时间",
                            "type":"string",
                            "value":"00:00-00:00",
                            "key":"time3_start_end",
                            "maxLength":11
                        }
                    ],
                    "groupKey":"force_led_open_door"
                },
                {
                    "groupName":"闸机配置",
                    "item":[
                        {
                            "minValue":0,
                            "readonly":0,
                            "maxValue":100000,
                            "name":"抬闸脉冲时长(ms)",
                            "type":"integer",
                            "value":2000,
                            "key":"up_gate"
                        },
                        {
                            "minValue":0,
                            "readonly":0,
                            "maxValue":65535,
                            "name":"落闸脉冲时长(ms)",
                            "type":"integer",
                            "value":1000,
                            "key":"down_gate"
                        }
                    ],
                    "groupKey":"gate_setup"
                },
                {
                    "groupName":"一键复位配置",
                    "item":[
                        {
                            "readonly":0,
                            "name":"复位按键使能",
                            "type":"boolean",
                            "value":1,
                            "key":"resetEnable"
                        }
                    ],
                    "groupKey":"one_key_reset"
                }
            ],
            "classifyKey":"devs_config",
            "classifyName":"外设配置"
        },
        {
            "groups":[
                {
                    "groupName":"系统重启",
                    "item":[
                        {
                            "readonly":0,
                            "name":"自动重启系统",
                            "type":"boolean",
                            "value":0,
                            "key":"auto_reboot"
                        },
                        {
                            "readonly":0,
                            "name":"时间",
                            "type":"string",
                            "value":"03:00:00",
                            "key":"time",
                            "maxLength":8
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2,
                                3,
                                4,
                                5,
                                6,
                                7
                            ],
                            "name":"星期",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "每天",
                                "星期天",
                                "星期一",
                                "星期二",
                                "星期三",
                                "星期四",
                                "星期五",
                                "星期六"
                            ],
                            "value":4,
                            "key":"week"
                        },
                        {
                            "readonly":0,
                            "optionValue":[
                                0,
                                1,
                                2
                            ],
                            "name":"日志级别",
                            "optionValueType":"integer",
                            "type":"enum",
                            "optionName":[
                                "最多",
                                "中等",
                                "最少"
                            ],
                            "value":0,
                            "key":"log_level"
                        }
                    ],
                    "groupKey":"system_reboot"
                }
            ],
            "classifyKey":"sys_maintain",
            "classifyName":"系统维护"
        }
    ],
    "desc":"Success"
}

module.exports = {
    json:json
  }

